project:
    title: "Usage Examples for Amplicon-tk"
    output-dir: docs
    post-render: just readme

    toc: true
    number-sections: true
    # bibliography: references.bib

    execute:
        freeze: auto
